config/routes.rb
SimpleBanking::Application.routes.draw do

  get "transfers/new"

  get "transfers/create"

  get 'log_out' => 'sessions#destroy',  :as => 'log_out'
  get 'log_in'  => 'sessions#new',      :as => 'log_in'
  get 'sign_up' => 'users#new',         :as => 'sign_up'
  resources :sessions

  root :to => 'home#demo'
  root :to => 'home#index'
  get 'home/demo'
  get 'home/index', as: 'home_index'
  resources :users do
    collection do
      post 'reset_sample_data'
    end
    resources :transfers
  end
  resources :transfers

end

app/models/account.rb
class Account < ActiveRecord::Base

  attr_accessible :balance_in_cents, :balance, :user_id

  belongs_to :user
  validates_presence_of :user_id, :balance_in_cents
  validates_numericality_of :balance_in_cents,
                            greater_than_or_equal_to: 0,
                            only_integer: true,
                            allow_nil: false

  def balance
    balance_in_cents / 100.00
  end

  def balance=(value)
    self.balance_in_cents= (value * 100).to_i
  end

  def label_method
    "Account #1 of : #{user.login}"
  end
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base

  belongs_to :origin,      :class_name => "Account", :foreign_key => "origin_id"
  belongs_to :destination, :class_name => "Account", :foreign_key => "destination_id"

  attr_accessible :origin_id, :origin, :destination_id, :destination, :amount, :amount_in_cents,
                  :origin_attributes, :destination_attributes

  validates_presence_of :origin_id, :destination_id, :amount_in_cents, :amount

  before_save   :patch_ensure_amounts_in_cent_is_number
  def patch_ensure_amounts_in_cent_is_number
    self.amount_in_cents= amount_in_cents.to_f
  end

  def amount
    amount_in_cents.to_i / 100.00
  end

  def amount=(value)
    self.amount_in_cents= (value * 100).to_i
  end

  def self.perform(source_account, dest_account, amount)
    tr = Transfer.new(origin: source_account, destination: dest_account, amount: amount)
    tr.save!
    tr
  end

  validate :amount_is_valid
  validate :destination_is_valid

    def amount_is_valid
      errors.add(:amount, "#{amount} is too much. Your balance is #{origin.balance}") if origin && amount > origin.balance
    end
    def destination_is_valid
      unless origin && destination && origin != destination
        errors.add(:destination, "you cannot transfer money to yourself")
      end
    end


  before_create :update_balances

  def  update_balances
    change_balance(origin,      -amount)
    change_balance(destination, amount)
  end

private

  def self.change_balance(source_account, amount)
    source_account.balance = source_account.balance + amount
    source_account.save!
  end

  def change_balance(source_account, amount)
    source_account.balance = source_account.balance + amount
    source_account.save!
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  after_create  :create_linked_account

  delegate :balance, :balance_in_cents, to: :account

  def create_linked_account
    self.build_account(balance: 0).save!
  end


  has_one :account
  has_many :transfers, :class_name => "Transfer", :foreign_key => "origin_id"
  has_many :transfers_credit, :class_name => "Transfer", :foreign_key => "destination_id"

  has_secure_password

  attr_accessible :login, :name, :password, :password_confirmation

  validates_presence_of :name, :login
  validates_uniqueness_of :login

  def admin?
    login == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :https_redirect


  def authorize
    unless current_user.present?
      redirect_to log_in_path, alert: "Not authorized : you must login first"
    end
  end

  def authorize_admin_only
    unless current_user.try(:admin?)
      redirect_to log_in_path, alert: "Not authorized : ADMIN only"
    end
  end

  def authorize_owner_or_admin_only
    unless current_user && (current_user.admin? || current_user == @user)
      redirect_to log_in_path, alert: "Not authorized"
    end
  end

private
  def https_redirect
    if ENV["ENABLE_HTTPS"] == "yes"
      if request.ssl? && !use_https? || !request.ssl? && use_https?
        protocol = request.ssl? ? "http" : "https"
        flash.keep
        redirect_to protocol: "#{protocol}://", status: :moved_permanently
      end
    end
  end

  def use_https?
    true # Override in other controllers
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def demo
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_login(params[:login])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      if user.admin?
        redirect_to users_path, :notice => "Logged in!"
      else
        redirect_to user_path(user), :notice => "Logged in!"
      end

    else
      flash.now.alert = "Invalid login or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_index_path, :notice => "Logged out!"
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_filter :authorize, only: [:new, :create, :index]

  def new
    if current_user.balance_in_cents == 0
      redirect_to current_user, alert: "Your balance is 0; you cannot transfer any money"
    else
      @transfer = Transfer.new(origin_id: current_user.id)
    end

  end

  def create
    source = Account.find_by_id(params[:transfer][:origin_id])
    dest   = Account.find_by_id(params[:transfer][:destination_id])
    amount = params[:transfer][:amount].presence.try(:to_f)
    @transfer =Transfer.new(origin: source, destination: dest, amount: amount)
    if @transfer.save
      redirect_to current_user, notice: "#{number_to_currency(@transfer.amount)} transferred."
    else
      render action: 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :get_user, only: [:show, :edit, :update, :destroy]
  def get_user
    @user = User.find(params[:id])
  end

  before_filter :authorize_owner_or_admin_only, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, :notice => "User #{@user.login} successfully signed up!" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def reset_sample_data
    require 'rake'
    Rake::Task.clear                  # necessary to avoid tasks being loaded several times in dev mode
    SimpleBanking::Application.load_tasks
    Rake::Task['db:seed'].reenable    # in case you're going to invoke the same task second time.
    Rake::Task['db:seed'].invoke
    redirect_to home_index_path, notice: "Sample Data was reset with #{User.count} users : #{User.all.collect(&:login).join(', ')}"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/demo.html.haml
%h1 Demo

#myCarousel.carousel.slide.well.well-large
  .carousel-inner
    -#.item.active
      -#%img{:alt => "", :src => "../assets/slide-01.jpg"}/
      .container
        .carousel-caption
          %h1 Example headline.
          %p.lead Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
          %a.btn.btn-large.btn-primary{:href => "#"} Sign up today
    .item.active
      %img{:alt => "", :src => "../assets/slide-02.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-03.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-04.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-a1.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-14.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-b1.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-24.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-c1.jpg"}/
    .item
      %img{:alt => "", :src => "../assets/slide-thatsit.jpg"}/
      .container
        .carousel-caption
          = link_to "Start", '/home/index', class: 'btn btn-large btn-primary'

  %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"} ‹
  %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"} ›

app/views/home/index.html.haml
%pre
  <h4>Example of scenario</h4>
  \- reset the DB (the red button below)
  \- login as Administrator (login = admin/pwd = admin)
  As #admin#,
  \- #{link_to 'create a new user', new_user_path}&nbsp;
  in [Manage Users] <small>(ex: login = yourname/pwd = yourpwd)</small>
  \- transfer $1000 to the 2 other users, in [Your account]
  &nbsp;&nbsp; => observe that
  &nbsp;&nbsp; &nbsp;&nbsp; 1° your balance has been updated
  &nbsp;&nbsp; &nbsp;&nbsp; 2° 2 transfers appear in the transfer:debit history
  &nbsp;
  \- #{link_to 'logout', log_out_path}&nbsp; and
  \- #{link_to 'login', log_in_path}&nbsp; as another user
  \- transfer $100 to the 2 other users, in [Your account]
  &nbsp;&nbsp; => observe that
  &nbsp;&nbsp; &nbsp;&nbsp; 1° your balance has been updated
  &nbsp;&nbsp; &nbsp;&nbsp; 2° transfers appear  now in the 2 columgs : debit and credit
  &nbsp;



.alert.alert-info
  =link_to reset_sample_data_users_path, class: 'btn btn-danger', method: :post do
    %i.icon-refresh
    Reset the DB and populate it with 2 users :
    %br
    %br
    admin/admin
    %br
    test/test

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "SimpleBanking"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    -#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    -#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    -#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    -#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => home_index_path} SimpleBanking
          .container-fluid.nav-collapse
            %p.navbar-text.pull-right
              - if current_user
                Logged in as
                = link_to current_user.name, current_user
                &nbsp;|&nbsp;
                = link_to "Logout", log_out_path
              - else
                = link_to "Login", log_in_path

            %ul.nav
              %li
                = link_to users_path, class: '' do
                  %i.icon-user
                  All Users
              %li
                - if current_user
                  = link_to 'Your Account', current_user
                - else
                  = link_to 'Your Account', log_in_path
              %li

              %li
                - if current_user
                  = link_to new_user_transfer_path(current_user), :class => '' do
                    %i.icon-money
                    Transfer money
                - else
                  = link_to 'Transfer money', log_in_path

              - if controller.action_name == 'demo'
                %li
                  .container
                    = link_to "Start", home_index_path, class: 'btn-start btn btn-primary'
              - unless controller.action_name == 'demo'
                %li
                  .container
                    = link_to "DEMO", home_demo_path, class: 'btn-demo btn btn-warning'
    .container-fluid
      .row-fluid
        .span12
          = bootstrap_flash
          = yield
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/transfers/create.html.haml
%h1 Transfers#create
%p Find me in app/views/transfers/create.html.haml

app/views/transfers/new.html.haml
%h1 Transfer money


- @origins      = [@transfer.origin]
- @destinations = Account.all.reject{|a| a.id == @transfer.origin_id }

.well
  = simple_form_for @transfer, :html => { :class => 'form-horizontal' } do |f|
    = f.input :origin_id, collection: @origins, label_method: 'label_method'
    = f.input :destination_id, collection: @destinations, label_method: 'label_method'
    - your_balance = @transfer.origin.balance
    = f.input :amount, :hint => "Maximum #{number_to_currency your_balance}"



    .form-actions
      = f.submit 'Transfer money', :class => 'btn btn-primary'
      -#= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :login
  = f.input :password
  = f.input :password_confirmation

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1
    All Users
    .pull-right
      = link_to 'Sign-up new User', new_user_path, :class => 'btn btn-primary'

.well
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:name)
        %th= model_class.human_attribute_name(:login)
        %th balance
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user_path(user)
          %td= user.login
          %td= number_to_currency user.balance
          %td
            - if current_user.try(:admin?)
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1 Sign-up a new User
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1 Profile and Transfers

.span12
  .row
    .span4.well
      %table.table
        %tr
          %td{width: '25%'}
            %strong= model_class.human_attribute_name(:name) + ':'
          %td= @user.name

        %tr
          %td
            %strong= model_class.human_attribute_name(:login) + ':'
          %td= @user.login

        %tr
          %td
            %strong= model_class.human_attribute_name(:balance) + ':'
          %td
            = number_to_currency @user.balance
            = link_to new_user_transfer_path(@user), :class => 'btn btn-primary pull-right' do
              %i.icon-money
              Transfer money

      .form-actions
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
    .span8


.span12.transfers_history
  .well.span12
    %h2 Transfers History

    .span12
      %div.span5
        %h3 Debit
        %table.table.table-striped.table-bordered.table-hover.table-condensed
          %tr
            %th{width: '40%'} to
            %th{width: '20%'} amount
            %th{width: '40%'} to
          - @user.transfers.each do |tr|
            %tr.error
              %td= tr.destination.label_method
              %td.amount= tr.amount
              %td
                = time_ago_in_words(tr.created_at)
                ago


      %div.span5
        %h3  Credit
        %table.table.table-striped.table-bordered.table-hover.table-condensed
          %tr
            %th{width: '40%'} from
            %th{width: '20%'} amount
            %th{width: '40%'} to
          - @user.transfers_credit.each do |tr|
            %tr.success
              %td= tr.origin     .label_method
              %td.amount= tr.amount
              %td
                = time_ago_in_words(tr.created_at)
                ago